const colors = {
  light: {
    text: "#1A2E25",
    tint: "#2D6A4F",
    background: "#F0F7F4",
    foreground: "#1A2E25",
    card: "#FFFFFF",
    cardForeground: "#1A2E25",
    primary: "#2D6A4F",
    primaryForeground: "#FFFFFF",
    secondary: "#E4EFE9",
    secondaryForeground: "#1A2E25",
    muted: "#E4EFE9",
    mutedForeground: "#6B8F7E",
    accent: "#52B788",
    accentForeground: "#FFFFFF",
    destructive: "#DC3545",
    destructiveForeground: "#FFFFFF",
    border: "#C8DDD3",
    input: "#C8DDD3",
    success: "#40916C",
    warning: "#F4A261",
    warningForeground: "#FFFFFF",
  },
  dark: {
    text: "#E8F5EE",
    tint: "#52B788",
    background: "#0D1B14",
    foreground: "#E8F5EE",
    card: "#1A2E25",
    cardForeground: "#E8F5EE",
    primary: "#52B788",
    primaryForeground: "#0D1B14",
    secondary: "#1F3D2C",
    secondaryForeground: "#E8F5EE",
    muted: "#1F3D2C",
    mutedForeground: "#8FBFAB",
    accent: "#74C69D",
    accentForeground: "#0D1B14",
    destructive: "#E53E3E",
    destructiveForeground: "#FFFFFF",
    border: "#2D4F3A",
    input: "#2D4F3A",
    success: "#52B788",
    warning: "#F4A261",
    warningForeground: "#0D1B14",
  },
  radius: 16,
};

export default colors;
